//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedTasks
    {
        public Nullable<int> IdUser { get; set; }
        public int IdTask { get; set; }
        public int IdProject { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<System.DateTime> DeadlineDate { get; set; }
        public Nullable<System.DateTime> DateOfCompletion { get; set; }
    
        public virtual Projects Projects { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
