//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.AssignedTasks = new HashSet<AssignedTasks>();
        }
    
        public int IdTask { get; set; }
        public string Name { get; set; }
        public int IdDifficulti { get; set; }
        public int IdService { get; set; }
        public decimal Cost { get; set; }
        public int Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedTasks> AssignedTasks { get; set; }
        public virtual Difficulties Difficulties { get; set; }
        public virtual Services Services { get; set; }
    }
}
